export const Styles = {
  theBox: {
    color: '#40E0D0',
    display: 'flex',
    flexDirection: 'column',
  },
  iconSection: {
    display: 'flex',
    justifyContent: 'center',
  },
  contentSection: {
    position: 'relative',
    top: '-8px',
    height: '100%',
    width: '100%',
    border: 'solid 1px #40E0D0',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  tabLeft: {
    border: 'solid #40E0D0',
    height: '50px',
    width: '50px',
    borderRadius: '50%',
    borderWidth: '2px',
    display: 'flex',
    justifyContent: 'cemnter',
    alignItems: 'center',
  },
  tabRight: {
    border: 'solid #40E0D0',
    height: '50px',
    width: '50px',
    borderRadius: '50%',
    borderWidth: '2px',
    display: 'flex',
    justifyContent: 'cemnter',
    alignItems: 'center',
  },
  iconBox1: {
    border: 'solid #40E0D0',
    height: '100px',
    width: '100px',
    borderRadius: '0% 0% 50% 0%',
    borderWidth: '0px 0px 2px 0px',
  },
  tabFocus: {
    border: 'solid #40E0D0',
    height: '100px',
    width: '100px',
    borderRadius: '50% 50% 0% 0%',
    borderWidth: '8px 0px 0px 0px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconBox3: {
    border: 'solid #40E0D0',
    height: '100px',
    width: '100px',
    borderRadius: '0% 0% 0% 50%',
    borderWidth: '0px 0px 1px 0px',
  },
  transperantBoxSection: {
    display: 'flex',
  },
  contentSectionTransperantBox1: {
    height: '2px',
    background: 'black',
    width: '100px',
    position: 'relative',
    top: '0px',
    left: '-1px',
  },
  contentSectionTransperantBox2: {
    height: '2px',
    background: 'black',
    width: '190px',
    position: 'relative',
    top: '-2px',
    left: '-1px',
    border: 'solid',
    borderWidth: '2px 0px 0px 0px',
    borderColor: 'black',
    borderRadius: '100% 100% 0px 0px',
  },
  contentSectionTransperantBox3: {
    height: '2px',
    background: 'black',
    width: '100px',
    position: 'relative',
    top: '0px',
    left: '-1px',
  },
  contentBox: {
    width: '90%',
    height: '100%',
    border: 'solid 1px #40E0D0',
    marginTop: '20px',
  },
};
